import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import Navbar from "@/components/Navbar";
import "material-symbols";


const SFPro = localFont({
  src: [
    
    {
      path: "./font/SF-Pro-Text-Heavy.otf",
      weight:"800",
      style: "normal;",

    },
    {
      path: "./font/SF-Pro-Text-Bold.otf",
      weight:"700",
      style: "normal;",

    },
    {
      path: "./font/SF-Pro-Text-Semibold.otf",
      weight:"600",
      style: "normal;",

    },
    {
      path: "./font/SF-Pro-Text-Medium.otf",
      weight:"500",
      style: "normal;",
    },
        {
      path: "./font/SF-Pro-Text-Regular.otf",
      weight:"400",
      style: "normal;",
    },
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${SFPro.className} antialiased bg-[var(--bg-primary)] select-none`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
